
services:
  backend:
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_PASS=${MONGO_DB_PASS}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    depends_on:
      - mongo
  frontend:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the frontend Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: